# Generated by Django 3.0.4 on 2020-04-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='item',
            new_name='task',
        ),
    ]
